- name: calling vars from variable files
  hosts: mysql
  vars_files:
    - /home/ec2-user/Ansible_practice/cred.yml
    - vars.yml
  tasks:
    - name: print the varibales from var file
      ansible.builtin.debug:
        msg: This is {{Name}}, working as {{Position}} at {{Company}}.