- name: install the packages in loop
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: install the packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "vim", state: "absent" }
        - { name: "git", state: "absent" }
    - name: install the packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - "git"
        - "vim"
    