- name: command vs shell
  hosts: client
  become: yes
  #connection: local
  tasks:
    - name: using command module
      ansible.builtin.command: ls -lrth /tmp
      register: command_output

    - name: display command output
      ansible.builtin.debug:
        msg: "{{ command_output }}"

    - name: using shell module
      ansible.builtin.shell: ps -ef | grep ssh
      register: shell_output

    - name: display shell output
      ansible.builtin.debug:
        msg: "{{ shell_output }}"